version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: subscriptions_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscriptions
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d subscriptions"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  
  app:
    build:
      context: .
    container_name: subscriptions_app

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy
    
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:
